"""imagens.imagem nullable (comprovantes passam a ser salvos em disco)

Revision ID: 49d6daf02bae
Revises: 8e7a1adbde1d
Create Date: 2026-09-14 19:26:27.027486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '49d6daf02bae'
down_revision = '8e7a1adbde1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagens', schema=None) as batch_op:
        batch_op.alter_column('imagem',
               existing_type=postgresql.BYTEA(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagens', schema=None) as batch_op:
        batch_op.alter_column('imagem',
               existing_type=postgresql.BYTEA(),
               nullable=False)

    # ### end Alembic commands ###
