"""initial

Revision ID: 8e7a1adbde1d
Revises: 
Create Date: 2025-08-18 18:38:31.682142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e7a1adbde1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('despesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cidade', sa.String(length=255), nullable=True),
    sa.Column('local', sa.String(length=255), nullable=True),
    sa.Column('numero_documento', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('complemento', sa.Text(), nullable=False),
    sa.Column('data_registro', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nome_colaborador', sa.String(length=100), nullable=True),
    sa.Column('cnpj_cpf_local', sa.String(length=18), nullable=True),
    sa.Column('nome_empresa', sa.String(length=255), nullable=True),
    sa.Column('num_cartao', sa.String(length=4), nullable=True),
    sa.Column('nome_projeto', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('colaboradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('numero_cartao', sa.String(length=4), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('imagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('despesa_id', sa.Integer(), nullable=False),
    sa.Column('imagem', sa.LargeBinary(), nullable=False),
    sa.Column('data_upload', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=True),
    sa.Column('caminho', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['despesa_id'], ['despesas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('local', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('colaborador_projeto',
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('colaborador_id', 'projeto_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('colaborador_projeto')
    op.drop_table('projetos')
    op.drop_table('imagens')
    op.drop_table('colaboradores')
    op.drop_table('usuarios')
    op.drop_table('empresas')
    op.drop_table('despesas')
    # ### end Alembic commands ###
