"""adiciona imagens.compactada

Revision ID: b5935ffabaa0
Revises: 49d6daf02bae
Create Date: 2026-09-14 19:41:52.187400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5935ffabaa0'
down_revision = '49d6daf02bae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compactada', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagens', schema=None) as batch_op:
        batch_op.drop_column('compactada')

    # ### end Alembic commands ###
